[package]
name = "wc"
version = "0.1.0"
authors = ["Leonid Zhelyaskov <leonid.zhelyaskov@gebit.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
#args = "2.2"
